LearningDjangoFive/LearningDjangoFive/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^basicapp/', include('basicapp.urls')),
    url(r'^logout/$',views.user_logout, name='logout'),
    url(r'^special/', views.special, name='special')

]

LearningDjangoFive/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    url(r'^register/$',views.register, name='register'),
    url(r'^login/$', views.user_login, name='user_login')
]

LearningDjangoFive/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return self.user.username

LearningDjangoFive/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

LearningDjangoFive/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.


def index(request):
    return render(request, 'basicapp/index.html')


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basicapp/registration.html', {
        'registered': registered,
        'user_form': user_form,
        'profile_form': profile_form,
    })


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account is not active')
        else:
            print("Someone tried to login and failed!")
            return HttpResponse('Invalid login details supplied!')
    else:
        return render(request, 'basicapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("You are logged in, nice!")

LearningDjangoFive/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'basicapp:register' %}">Register</a></li>

                {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                    <li><a class="navbar-link" href="{% url 'special' %}">Special</a></li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'basicapp:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

<div class="container">
{% block body_block %}
{% endblock %}
</div>

</body>
</html>

LearningDjangoFive/templates/basicapp/index.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Welcome!</h1>
</div>
{% endblock %}

LearningDjangoFive/templates/basicapp/login.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
{% block body_block %}


    <div class="jumbotron">
    <h1>Please login</h1>
    <form method="post" action="{% url 'basicapp:user_login' %}">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter username">

        <label for="password"></label>
        <input type="password" name="password">

        <input type="submit" value="Login">

    </form>

    </div>


{% endblock %}

LearningDjangoFive/templates/basicapp/registration.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% load static %}

{% block body_block %}


    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {%  else %}
            <h1>Register here!</h1>
            <h3>Fill out the form:</h3>


            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value="Register">

            </form>

        {% endif %}

    </div>

{% endblock %}